### ISSUE TITLE
Changes from upstream?

### ISSUE THREAD

**Issue by kamranayub** [probablyup/wait-for-netlify-action#1]
Hey, thanks for forking my action and making some changes! It looks like you addressed some bugs? Was there a reason you went with a fork instead of proposing PRs with fixes? I'd have happily accepted them. I could understand if you planned to change the approach, where you may want your own fork. If yours works well I may just deprecate mine and switch to your fork.

**edit:** Testing your fork since I only use this action in one place. Looks like you may have fixed an issue with the timeout not being correctly respected.

**edit 2:** Yep, this is great, thanks for finding/fixing these issues. 🙏  I've tried to document the changes below for reference. I will go ahead and add a notice to my README to redirect people here. Since I have some existing content/videos that reference my fork, I _think_ I can archive it and it'll still work? I'll figure it out.

## Changes

- Fix issue with `max_timeout` not working correctly
- Change `site_name` to `site_id` to have a more stable reference ID to lookup
- Better waiting semantics for the deployment status
- For full history see: https://github.com/probablyup/wait-for-netlify-action/releases

**Comment by IanVS** [comment]
I see that this package is both ahead and behind the version from @kamranayub.  I'm a bit confused over which is the more stable/maintained fork to use.  

Also, it would be great if one of them could be updated to use node 16, since GitHub is now showing deprecation warnings for older actions that are still using Node 12.

**Comment by kamranayub** [comment]
I'll take a look, I think I intended to switch to this fork.

**Comment by kevinpainchaud** [comment]
> I see that this package is both ahead and behind the version from @kamranayub. I'm a bit confused over which is the more stable/maintained fork to use.
> 
> Also, it would be great if one of them could be updated to use node 16, since GitHub is now showing deprecation warnings for older actions that are still using Node 12.

Done ✅ https://github.com/probablyup/wait-for-netlify-action/pull/4

**Comment by quantizor** [comment]
Thanks @kevinpainchaud for performing the requested maintenance!
