### ISSUE TITLE
Action failing to hit site which is definitely accessible on typescript-eslint

### ISSUE THREAD

**Issue by JamesHenry** [probablyup/wait-for-netlify-action#5]
Hi @probablyup - We have just started using your action on [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint), thanks a lot for providing it to the community!

Sadly it seems to be behaving a little strangely for us, particularly on main branch runs.

Please see recording which shows that our website tests get stuck waiting for a deployment, despite that deployment definitely being accessible. I verified via the browser on the video, but I also did so via curl and received the 200 no problem:

https://user-images.githubusercontent.com/900523/220277791-c1efe227-b7b8-4831-88a9-44a7d589d5c0.mov

Here is that run for reference: https://github.com/typescript-eslint/typescript-eslint/actions/runs/4230119382/jobs/7347374647

Please could you take a look?

**Comment by quantizor** [comment]
Hey James, I actually don’t use Netlify anymore so I won’t be much help. If you’d like to propose a fix PR I’d be happy to take a look

**Comment by JamesHenry** [comment]
Thanks @probablyup and sorry for the delayed resolution here.

I have resolved this today by writing a lightweight action from scratch for us inline in the repo: 
https://github.com/typescript-eslint/typescript-eslint/blob/dbb9de6c4dc8246750d8ef5ccf209bff01e7ce7a/.github/actions/wait-for-netlify/index.js
